In [3]:
# emb_layer，输入可以是float，也可以是int哦
import tensorflow as tf
import numpy as np
emb_layer=tf.keras.layers.Embedding(input_dim=4,output_dim=4)
input_arr=np.random.randint(0,3,size=[10,3]).astype(np.float32)

emb_layer(input_arr)

<tf.Tensor: shape=(10, 3, 4), dtype=float32, numpy=
array([[[-0.00692995, -0.01828307,  0.02167258, -0.02317418],
        [-0.00692995, -0.01828307,  0.02167258, -0.02317418],
        [ 0.03865786, -0.0134825 , -0.03807016,  0.01790968]],

       [[ 0.03865786, -0.0134825 , -0.03807016,  0.01790968],
        [ 0.03865786, -0.0134825 , -0.03807016,  0.01790968],
        [ 0.01743201, -0.02088796,  0.03526458,  0.01196425]],

       [[ 0.01743201, -0.02088796,  0.03526458,  0.01196425],
        [ 0.01743201, -0.02088796,  0.03526458,  0.01196425],
        [ 0.01743201, -0.02088796,  0.03526458,  0.01196425]],

       [[ 0.03865786, -0.0134825 , -0.03807016,  0.01790968],
        [-0.00692995, -0.01828307,  0.02167258, -0.02317418],
        [ 0.03865786, -0.0134825 , -0.03807016,  0.01790968]],

       [[ 0.01743201, -0.02088796,  0.03526458,  0.01196425],
        [-0.00692995, -0.01828307,  0.02167258, -0.02317418],
        [-0.00692995, -0.01828307,  0.02167258, -0.02317418]],

       [

array([[1, 0, 0],
       [0, 2, 2],
       [1, 2, 1],
       [0, 2, 0],
       [2, 1, 2],
       [1, 1, 2],
       [1, 0, 0],
       [0, 1, 0],
       [2, 2, 1],
       [1, 0, 1]])