In [4]:
#embedding_lookup_sparse

import tensorflow as tf

embedding_param=tf.random.truncated_normal(shape=(3,4))

sparse_tensor=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[10,1]], values=[1,2,0,0], dense_shape=[3, 4])
print(embedding_param)
tf.nn.embedding_lookup_sparse(params=embedding_param,sp_ids=sparse_tensor,sp_weights=None)


tf.Tensor(
[[-1.26872     0.3412113   1.0939224  -0.793767  ]
 [-1.7712302   1.6600988  -1.3424066   1.3043035 ]
 [ 0.35535678 -0.8327109   1.6589825   0.39188293]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(11, 4), dtype=float32, numpy=
array([[-0.7079367 ,  0.41369393,  0.15828794,  0.8480932 ],
       [-1.26872   ,  0.3412113 ,  1.0939224 , -0.793767  ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.26872   ,  0.3412113 ,  1.0939224 , -0.793767  ]],
      dtype=float32)>