In [1]:
#embedding_lookup_sparse

import tensorflow as tf

embedding_param=tf.random.truncated_normal(shape=(3,4))

sparse_tensor=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[10,1]], values=[1,2,0,0], dense_shape=[3, 4])
print(embedding_param)
tf.nn.embedding_lookup_sparse(params=embedding_param,sp_ids=sparse_tensor,sp_weights=None)


tf.Tensor(
[[-0.28369153  0.22111179  1.905132    0.16127738]
 [-0.6138425   0.40119487  0.15611733 -0.25702414]
 [ 1.3703052  -0.33670297  0.2873767  -0.76371247]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(11, 4), dtype=float32, numpy=
array([[ 0.37823135,  0.03224595,  0.22174701, -0.5103683 ],
       [-0.28369153,  0.22111179,  1.905132  ,  0.16127738],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.28369153,  0.22111179,  1.905132  ,  0.16127738]],
      dtype=float32)>

In [2]:
embedding_param

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.28369153,  0.22111179,  1.905132  ,  0.16127738],
       [-0.6138425 ,  0.40119487,  0.15611733, -0.25702414],
       [ 1.3703052 , -0.33670297,  0.2873767 , -0.76371247]],
      dtype=float32)>