In [3]:
#embedding_lookup_sparse

import tensorflow as tf

embedding_param=tf.random.truncated_normal(shape=(3,4))

sparse_tensor=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[2,1]], values=[1,2,0,0], dense_shape=[3, 4])
print(embedding_param)
tf.nn.embedding_lookup_sparse(params=embedding_param,sp_ids=sparse_tensor,sp_weights=None)


tf.Tensor(
[[ 0.8635217   1.6986538  -0.7250104  -1.2296655 ]
 [ 1.2955146  -0.23318473 -1.1222814  -0.81240666]
 [ 0.5230169  -0.02516606  0.04653292  0.99231285]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.90926576, -0.1291754 , -0.5378743 ,  0.08995309],
       [ 0.8635217 ,  1.6986538 , -0.7250104 , -1.2296655 ],
       [ 0.8635217 ,  1.6986538 , -0.7250104 , -1.2296655 ]],
      dtype=float32)>

In [2]:
embedding_param

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.28369153,  0.22111179,  1.905132  ,  0.16127738],
       [-0.6138425 ,  0.40119487,  0.15611733, -0.25702414],
       [ 1.3703052 , -0.33670297,  0.2873767 , -0.76371247]],
      dtype=float32)>

In [5]:
import tensorflow as tf

embedding_param=tf.random.truncated_normal(shape=(3,4))
# 实际上这个sparse_tensor是不合法的，但embedding_lookup_sparse并没有校验合法性
sparse_tensor=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[10,1]], values=[1,2,0,0], dense_shape=[3, 4])
print(embedding_param)
tf.nn.embedding_lookup_sparse(params=embedding_param,sp_ids=sparse_tensor,sp_weights=None)

tf.Tensor(
[[ 1.4632641   0.38111594 -1.0705905  -0.6842591 ]
 [ 0.91204876  0.8336627   0.5382726   0.79232466]
 [-1.5374717   1.0129488  -0.27162835 -0.22637124]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(11, 4), dtype=float32, numpy=
array([[-0.31271145,  0.92330575,  0.13332213,  0.28297672],
       [ 1.4632641 ,  0.38111594, -1.0705905 , -0.6842591 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.4632641 ,  0.38111594, -1.0705905 , -0.6842591 ]],
      dtype=float32)>

In [7]:
print(sparse_tensor)


SparseTensor(indices=tf.Tensor(
[[ 0  0]
 [ 0  1]
 [ 1  2]
 [10  1]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 0 0], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [12]:
# sp_weights

import tensorflow as tf

embedding_param=tf.random.truncated_normal(shape=(3,4))
sp_ids=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[2,1]], values=[1,2,1,1], dense_shape=[3, 4])
sp_weights=tf.sparse.SparseTensor(indices=[[0, 0],[0,1], [1, 2],[2,1]], values=[1,2,1,2], dense_shape=[3, 4])
print(embedding_param)
tf.nn.embedding_lookup_sparse(params=embedding_param,sp_ids=sp_ids,sp_weights=sp_weights,combiner="sum")

tf.Tensor(
[[-0.7208965   0.35720897  1.2735151   0.59348965]
 [-0.2979291  -0.31340468  0.760616   -0.75253844]
 [ 1.0593032  -1.076854    0.67688084  0.30121157]], shape=(3, 4), dtype=float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.8206773 , -2.4671125 ,  2.1143777 , -0.15011531],
       [-0.2979291 , -0.31340468,  0.760616  , -0.75253844],
       [-0.5958582 , -0.62680936,  1.521232  , -1.5050769 ]],
      dtype=float32)>