In [3]:
# 构造一个sparseTensor
import tensorflow as tf
sparse_tensor=tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
dense_tensor=tf.constant([[1, 0, 0, 0],
 [0, 0, 2, 0],
 [0, 0, 0, 0]])

print(sparse_tensor)
print(dense_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [5]:
import tensorflow as tf
# sparse和tensor互转

dense_tensor=tf.constant([[1, 0, 0, 0],
 [0, 0, 2, 0],
 [0, 0, 0, 0]])
arr_idx = tf.where(tf.not_equal(dense_tensor, 0))
# gather_nd这个操作就是根据arr_idx的指示，从dense_tensor提取值，最终的结果shape由arr_idx决定
# 而arr_idx的0轴的每个元素都是一个坐标，因此arr_values就是一个一维度向量
arr_values=tf.gather_nd(dense_tensor, arr_idx)
sparse_tensor = tf.SparseTensor(arr_idx,arr_values,dense_shape=dense_tensor.shape)

print(arr_idx)
print(arr_values)
print(sparse_tensor)
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64)
tf.Tensor([1 2], shape=(2,), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [14]:
# sparseTensor与dataset
# dataset也可以持有sparseTensor哦
import tensorflow as tf
import numpy as np
ds=tf.data.Dataset.from_tensor_slices([np.reshape(np.random.choice([0,1],size=100),newshape=(10,10))])

def dense_to_sparse(dense_tensor):
    idx = tf.where(tf.not_equal(dense_tensor, 0))
    values=tf.gather_nd(dense_tensor, arr_idx)
    return tf.SparseTensor(arr_idx,arr_values,dense_shape=dense_tensor.shape)

for sample in ds:
    print(sample)

sparse_ds=ds.map(dense_to_sparse)
for sample in sparse_ds:
    print(sample)

tf.Tensor(
[[0 1 1 0 1 1 1 1 1 1]
 [1 1 1 1 1 0 1 0 1 0]
 [1 0 0 1 0 1 1 1 1 0]
 [0 0 0 0 0 1 1 0 0 1]
 [1 0 1 0 0 0 0 0 1 1]
 [0 1 0 0 1 0 0 1 0 1]
 [0 1 0 0 0 0 1 0 0 1]
 [0 1 1 0 0 0 1 1 0 0]
 [0 1 1 0 0 1 0 1 0 0]
 [0 1 0 0 1 1 0 0 1 1]], shape=(10, 10), dtype=int32)
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([10 10], shape=(2,), dtype=int64))


In [10]:
np.random.choice([0,1],size=100)

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0])