In [1]:
import tensorflow as tf
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


In [2]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [3]:
# To use a layer, simply call it.
layer(tf.zeros([10, 5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.07820755, -0.35472423, -0.33291033, -0.12229198,  0.13671947,
          0.04017973,  0.30425435, -0.17597681,  0.3455888 ,  0.28213495],
        [-0.4871316 , -0.4500637 ,  0.5276838 ,  0.4304729 , -0.60655206,
         -0.02040946, -0.39246994,  0.58272356,  0.01984656, -0.31247538],
        [-0.07082051, -0.5907985 ,  0.20747393, -0.45610112, -0.17349648,
         -0.55453146, -0.47197318,  0.556495  ,  0.06004244,  0.17278308],
        [-0.32963955, -0.28614366,  0.57288104, -0.5853654 ,  0.1968996 ,
         -0.21841267,  0.32983965, -0.5548594 , -0.6170287 ,  0.43566614],
        [ 0.02472442, -0.0730257 , -0.24351996, -0.456232  ,  0.14912397,
          0.29163253,  0.26199102,  0.14669615,  0.24232161, -0.6131984 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.07820755, -0.35472423, -0.33291033, -0.12229198,  0.13671947,
          0.04017973,  0.30425435, -0.17597681,  0.3455888 ,  0.28213495],
        [-0.4871316 , -0.4500637 ,  0.5276838 ,  0.4304729 , -0.60655206,
         -0.02040946, -0.39246994,  0.58272356,  0.01984656, -0.31247538],
        [-0.07082051, -0.5907985 ,  0.20747393, -0.45610112, -0.17349648,
         -0.55453146, -0.47197318,  0.556495  ,  0.06004244,  0.17278308],
        [-0.32963955, -0.28614366,  0.57288104, -0.5853654 ,  0.1968996 ,
         -0.21841267,  0.32983965, -0.5548594 , -0.6170287 ,  0.43566614],
        [ 0.02472442, -0.0730257 , -0.24351996, -0.456232  ,  0.14912397,
          0.29163253,  0.26199102,  0.14669615,  0.24232161, -0.6131984 ]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [7]:
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    # build存在的好处在文档里说明过，可以在运行时实时计算形状
    print("build")
    self.kernel = self.add_weight("kernel",
                                  shape=[int(input_shape[-1]),
                                         self.num_outputs])

  def call(self, input):
    print(input)
    return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)

In [8]:
_ = layer(tf.zeros([10, 5])) # Calling the layer `.builds` it.
# 执行的是__call__方法，我猜这个方法里会执行build与call

build
tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)


In [12]:
class MyLayer(tf.keras.layers.Layer):
  def __init__(self):
    super(MyLayer, self).__init__()

  def build(self, input_shape):
    self.embed_layer1=tf.keras.layers.Embedding(input_dim=11,output_dim=4)
    self.embed_layer2=tf.keras.layers.Embedding(input_dim=11,output_dim=4)
    self.embed_layer3=tf.keras.layers.Embedding(input_dim=11,output_dim=4)

  def call(self,input):
    print(input) # 这个input是eagerTensor
    cate_id,shop_id,brand_id=input[0],input[1],input[2]
    cate_emb=self.embed_layer1(cate_id)
    shop_emb=self.embed_layer2(shop_id)
    brand_emb=self.embed_layer3(brand_id)
    return tf.concat((cate_emb,shop_emb,brand_emb),axis=0)

layer = MyLayer()
layer([0,1,2])
print([var.name for var in layer.trainable_variables])

[<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>]
['my_layer_3/embedding_9/embeddings:0', 'my_layer_3/embedding_10/embeddings:0', 'my_layer_3/embedding_11/embeddings:0']


In [8]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


In [9]:
layer.variables

[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.50721896, -0.47232395, -0.1973064 ,  0.6243182 , -0.52000153,
         -0.33274007, -0.54664564, -0.24344924,  0.20886755,  0.52766436],
        [-0.10194582, -0.26520237,  0.40553063, -0.1508505 , -0.2437858 ,
          0.00684595, -0.43593943,  0.5112054 , -0.01449776,  0.62161833],
        [ 0.2649358 , -0.39786154, -0.38311344, -0.61532545,  0.41653258,
          0.37220067, -0.5659071 ,  0.40570682,  0.02277929,  0.1916483 ],
        [ 0.6030242 ,  0.40876168,  0.43201512,  0.5830526 ,  0.3149292 ,
         -0.4627903 ,  0.20632708,  0.36614305,  0.4345067 , -0.6315632 ],
        [ 0.07500148, -0.23751885, -0.13329414,  0.43967134,  0.40748554,
         -0.06890881,  0.47799903,  0.6097793 , -0.455846  , -0.25933594]],
       dtype=float32)>]

In [12]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

In [13]:
block(tf.ones([1, 2, 3, 3])) 


<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0.94029474, 0.9919794 , 1.0313917 ],
         [0.94029474, 0.9919794 , 1.0313917 ],
         [0.94029474, 0.9919794 , 1.0313917 ]],

        [[0.94029474, 0.9919794 , 1.0313917 ],
         [0.94029474, 0.9919794 , 1.0313917 ],
         [0.94029474, 0.9919794 , 1.0313917 ]]]], dtype=float32)>